# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentseasy',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
