# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0004_auto_20161104_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentseasy',
            name='author',
            field=models.IntegerField(null=True),
        ),
    ]
