# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0005_auto_20161104_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentseasy',
            name='childcomment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commentseasy',
            name='parentcomment',
            field=models.IntegerField(null=True),
        ),
    ]
