# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0006_auto_20161109_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentseasy',
            old_name='likes',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='commentseasy',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
