# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0009_auto_20161110_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentseasy',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
