# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0011_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentseasy',
            old_name='downvotes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='downvote',
            new_name='liked',
        ),
        migrations.RemoveField(
            model_name='commentseasy',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='upvote',
        ),
    ]
