# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0012_auto_20161111_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='postid',
            new_name='commentid',
        ),
    ]
