# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0013_auto_20161111_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Likes',
        ),
        migrations.RenameField(
            model_name='commentseasy',
            old_name='likes',
            new_name='total_likes',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='commentid',
            new_name='comment',
        ),
    ]
