# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0014_auto_20161111_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='userid',
            new_name='user',
        ),
    ]
