# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0015_auto_20161111_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentseasy',
            options={'ordering': ('-timestamp',)},
        ),
    ]
