# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0016_auto_20161111_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentseasy',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='commentseasy',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
