# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_commentseasy', '0017_auto_20161111_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentseasy',
            name='childcomment',
        ),
        migrations.AlterField(
            model_name='commentseasy',
            name='parentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_commentseasy.CommentsEasy'),
        ),
    ]
